# dùng để chạy nhiều container cùng lúc: 1 lệnh → chạy toàn hệ thống

services:
  postgres:
    image: postgres:16-alpine
    container_name: pg_nestjs_ecommerce_dev
    restart: unless-stopped # container tự restart nếu crash.
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - '${DB_PORT}:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data # lưu dữ liệu database bền vững
    networks:
      - ecommerce_net
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U ${DB_USER} -d ${DB_NAME}']
      interval: 10s
      timeout: 5s
      retries: 5

  app:
    build:
      context: .
      dockerfile: Dockerfile
      target: production
    container_name: nestjs_ecommerce_app_dev
    restart: unless-stopped
    env_file:
      - .env
    environment:
      DATABASE_URL: postgresql://${DB_USER}:${DB_PASSWORD}@postgres:${DB_PORT}/${DB_NAME}?schema=public
    ports:
      - '${PORT}:3000'
    depends_on:
      postgres:
        condition: service_healthy # app chỉ start khi PostgreSQL healthcheck pass
    networks:
      - ecommerce_net

volumes:
  postgres_data:

networks:
  ecommerce_net:
    driver: bridge
